// Données intégrées directement dans le fichier JavaScript

const championsLeagueData = [
    { year: 2023, club: "Manchester City" },
    { year: 2022, club: "Real Madrid" },
    { year: 2021, club: "Chelsea" },
    { year: 2020, club: "Bayern Munich" },
    { year: 2019, club: "Liverpool" },
    { year: 2018, club: "Real Madrid" },
    { year: 2017, club: "Real Madrid" },
    { year: 2016, club: "Real Madrid" },
    { year: 2015, club: "Barcelona" },
    { year: 2014, club: "Real Madrid" },
    { year: 2013, club: "Bayern Munich" },
    { year: 2012, club: "Chelsea" },
    { year: 2011, club: "Barcelona" },
    { year: 2010, club: "Inter Milan" },
    { year: 2009, club: "Barcelona" },
    { year: 2008, club: "Manchester United" },
    { year: 2007, club: "Milan" },
    { year: 2006, club: "Barcelona" },
    { year: 2005, club: "Liverpool" },
    { year: 2004, club: "Porto" },
    { year: 2003, club: "Milan" },
    { year: 2002, club: "Real Madrid" },
    { year: 2001, club: "Bayern Munich" },
    { year: 2000, club: "Real Madrid" },
    { year: 1999, club: "Manchester United" },
    { year: 1998, club: "Real Madrid" },
    { year: 1997, club: "Borussia Dortmund" },
    { year: 1996, club: "Juventus" },
    { year: 1995, club: "Ajax" },
    { year: 1994, club: "AC Milan" },
    { year: 1993, club: "Marseille" },
    { year: 1992, club: "Barcelona" },
    { year: 1991, club: "Red Star Belgrade" },
    { year: 1990, club: "AC Milan" },
    { year: 1989, club: "AC Milan" },
    { year: 1988, club: "PSV Eindhoven" },
    { year: 1987, club: "Porto" },
    { year: 1986, club: "Steaua Bucharest" },
    { year: 1985, club: "Juventus" },
    { year: 1984, club: "Liverpool" },
    { year: 1983, club: "Hamburg" },
    { year: 1982, club: "Barcelona" },
    { year: 1981, club: "Liverpool" },
    { year: 1980, club: "Nottingham Forest" },
    { year: 1979, club: "Nottingham Forest" },
    { year: 1978, club: "Liverpool" },
    { year: 1977, club: "Liverpool" },
    { year: 1976, club: "Bayern Munich" },
    { year: 1975, club: "Bayern Munich" },
    { year: 1974, club: "Bayern Munich" },
    { year: 1973, club: "Ajax" },
    { year: 1972, club: "Ajax" },
    { year: 1971, club: "Ajax" },
    { year: 1970, club: "Celtic" },
    { year: 1969, club: "Milan" },
    { year: 1968, club: "Manchester United" },
    { year: 1967, club: "Celtic" },
    { year: 1966, club: "Real Madrid" },
    { year: 1965, club: "Inter Milan" },
    { year: 1964, club: "Inter Milan" },
    { year: 1963, club: "Milan" },
    { year: 1962, club: "Benfica" },
    { year: 1961, club: "Benfica" },
    { year: 1960, club: "Real Madrid" },
    { year: 1959, club: "Real Madrid" },
    { year: 1958, club: "Real Madrid" },
    { year: 1957, club: "Real Madrid" },
    { year: 1956, club: "Real Madrid" }
];

const championshipsData = [
    { year: 2023, championship: "Ligue 1", winner: "Paris Saint-Germain" },
    { year: 2023, championship: "Premier League", winner: "Manchester City" },
    { year: 2023, championship: "La Liga", winner: "Barcelona" },
    { year: 2023, championship: "Serie A", winner: "Napoli" },
    { year: 2022, championship: "Ligue 1", winner: "Paris Saint-Germain" },
    { year: 2022, championship: "Premier League", winner: "Manchester City" },
    { year: 2022, championship: "La Liga", winner: "Real Madrid" },
    { year: 2022, championship: "Serie A", winner: "AC Milan" },
    { year: 2021, championship: "Ligue 1", winner: "Paris Saint-Germain" },
    { year: 2021, championship: "Premier League", winner: "Manchester City" },
    { year: 2021, championship: "La Liga", winner: "Atletico Madrid" },
    { year: 2021, championship: "Serie A", winner: "Inter Milan" },
    { year: 2020, championship: "Ligue 1", winner: "Paris Saint-Germain" },
    { year: 2020, championship: "Premier League", winner: "Liverpool" },
    { year: 2020, championship: "La Liga", winner: "Real Madrid" },
    { year: 2020, championship: "Serie A", winner: "Juventus" },
    // ... Ajoutez d'autres années jusqu'en 1932
    { year: 1932, championship: "Ligue 1", winner: "Olympique Lillois" }
];

const ballonDorData = [
    { year: 2023, player: "Lionel Messi" },
    { year: 2022, player: "Karim Benzema" },
    { year: 2021, player: "Lionel Messi" },
    { year: 2020, player: "Robert Lewandowski" },
    { year: 2019, player: "Lionel Messi" },
    { year: 2018, player: "Luka Modric" },
    { year: 2017, player: "Cristiano Ronaldo" },
    { year: 2016, player: "Cristiano Ronaldo" },
    { year: 2015, player: "Lionel Messi" },
    { year: 2014, player: "Cristiano Ronaldo" },
    { year: 2013, player: "Cristiano Ronaldo" },
    { year: 2012, player: "Lionel Messi" },
    { year: 2011, player: "Lionel Messi" },
    { year: 2010, player: "Lionel Messi" },
    { year: 2009, player: "Lionel Messi" },
    { year: 2008, player: "Cristiano Ronaldo" },
    { year: 2007, player: "Kaka" },
    { year: 2006, player: "Fabio Cannavaro" },
    { year: 2005, player: "Ronaldinho" },
    { year: 2004, player: "Andriy Shevchenko" },
    { year: 2003, player: "Michael Owen" },
    { year: 2002, player: "Ronaldo" },
    { year: 2001, player: "Michael Owen" },
    { year: 2000, player: "Luis Figo" },
    { year: 1999, player: "Rivaldo" },
    { year: 1998, player: "Zinedine Zidane" },
    { year: 1997, player: "Ronaldo" },
    { year: 1996, player: "George Weah" },
    { year: 1995, player: "Johan Cruyff" },
    { year: 1994, player: "Hristo Stoichkov" },
    { year: 1993, player: "Marco van Basten" },
    { year: 1992, player: "Johan Cruyff" },
    { year: 1991, player: "Jean-Pierre Papin" },
    { year: 1990, player: "Lothar Matthaus" },
    { year: 1989, player: "Marco van Basten" },
    { year: 1988, player: "Ruud Gullit" },
    { year: 1987, player: "Ruud Gullit" },
    { year: 1986, player: "Igor Belanov" },
    { year: 1985, player: "Michel Platini" },
    { year: 1984, player: "Michel Platini" },
    { year: 1983, player: "Michel Platini" },
    { year: 1982, player: "Paolo Rossi" },
    { year: 1981, player: "Karl-Heinz Rummenigge" },
    { year: 1980, player: "Karl-Heinz Rummenigge" },
    { year: 1979, player: "Kevin Keegan" },
    { year: 1978, player: "Kevin Keegan" },
    { year: 1977, player: "Johan Cruyff" },
    { year: 1976, player: "Johan Cruyff" },
    { year: 1975, player: "Oleg Blokhin" },
    { year: 1974, player: "Johan Cruyff" },
    { year: 1973, player: "Johan Cruyff" },
    { year: 1972, player: "Johan Cruyff" },
    { year: 1971, player: "Johan Cruyff" },
    { year: 1970, player: "Gerd Muller" },
    { year: 1969, player: "Gianna Rivera" },
    { year: 1968, player: "George Best" },
    { year: 1967, player: "Eusébio" },
    { year: 1966, player: "Bobby Charlton" },
    { year: 1965, player: "Johan Cruyff" },
    { year: 1964, player: "Denis Law" },
    { year: 1963, player: "Jimmy Greaves" },
    { year: 1962, player: "Josef Masopust" },
    { year: 1961, player: "Omar Sivori" },
    { year: 1960, player: "Luis Suarez" },
    { year: 1959, player: "Alfredo Di Stefano" },
    { year: 1958, player: "Alfredo Di Stefano" },
    { year: 1957, player: "Alfredo Di Stefano" },
    { year: 1956, player: "Stanley Matthews" }
];

// Fonction pour remplir les listes
function populateList(elementId, items, ...fields) {
    const list = document.getElementById(elementId);
    list.innerHTML = '';
    items.forEach(item => {
        const itemElement = document.createElement('div');
        itemElement.textContent = fields.map(field => item[field]).join(' - ');
        list.appendChild(itemElement);
    });
}

// Remplir les sections après le chargement du DOM
document.addEventListener('DOMContentLoaded', function() {
    populateList('champions-league-list', championsLeagueData, 'year', 'club');
    populateList('championships-list', championshipsData, 'year', 'championship', 'winner');
    populateList('ballon-dor-list', ballonDorData, 'year', 'player');
});
